FROM python:3.12-slim
RUN apt-get update && apt-get install -y
WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY stock_pipeline.py .
COPY run.sh .
RUN chmod +x run.sh

CMD ["./run.sh"]
